### ISSUE TITLE
rename "meta" field in the query service API to "userMeta" to align with the report service API

### ISSUE THREAD

**Issue by Foxcapades** [VEuPathDB/service-multi-blast#168]
Locations:

- [x] raml
- [x] sdk type: query job list entry
- [x] sdk type: query job post request
- [x] sdk type: query job details
- [x] sdk type: query job patch request
- [x] conversion methods
- [x] controller methods
- [x] service methods
- [x] Json paths
